services:
  - type: web
    name: leetcode-tracker-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: leetcode-db
          property: connectionString

databases:
  - name: leetcode-db
    plan: free
